baseURL = 'https://bibhasdn.com/'
languageCode = 'en-us'
title = 'Occasional and random thoughts of Bibhas'
theme = 'archie'
paginate = 10
pluralizelisttitles = false   # removes the automatically appended "s" on sidebar entries
copyright = "© Bibhas"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
	mode="toggle" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Blah blah"
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support
	customcss = ["css/custom.css"]

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/iambibhas"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/bibhasdn/"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4