baseURL = 'https://bibhasdn.com/'
languageCode = 'en-us'
title = 'Bibhas Debnath'
theme = 'archie'
paginate = 10
pluralizelisttitles = false   # removes the automatically appended "s" on sidebar entries
copyright = "© Bibhas D"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
	mode="toggle" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = """
Non-tech first. Tech later. Nothing brings me more joy than visiting a new place or doing something new or breaking a fear.
I also like to help people find new places/things to explore. If you are in a community that values that, sign me up.
Outside work, I'd be more interested if someone talked about their passions, hobbies, interests, dreams instead of the latest tech.
I do mostly backend dev, plus Ops. Tools no bar as long as it solves problem.
	"""
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support
	customcss = ["css/custom.css"]

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/iambibhas"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/bibhasdn/"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/bibhasdn"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[menu.main]]
name = "Resume"
url = "https://cv.bibhasdn.com"
weight = 5